//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandicapModel.Admin.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IOPaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOPaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandicapModel.Admin.IO.IOPaths", typeof(IOPaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alst.xml.
        /// </summary>
        internal static string athleteDataFile {
            get {
                return ResourceManager.GetString("athleteDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PtsTbl.xml.
        /// </summary>
        internal static string athletePointTableFile {
            get {
                return ResourceManager.GetString("athletePointTableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RsTbl.xml.
        /// </summary>
        internal static string athleteResultsTable {
            get {
                return ResourceManager.GetString("athleteResultsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clst.xml.
        /// </summary>
        internal static string clubDataFile {
            get {
                return ResourceManager.GetString("clubDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClbTbl.xml.
        /// </summary>
        internal static string clubPointsTableFile {
            get {
                return ResourceManager.GetString("clubPointsTableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\cf.
        /// </summary>
        internal static string configurationPath {
            get {
                return ResourceManager.GetString("configurationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.txt.
        /// </summary>
        internal static string currentEvent {
            get {
                return ResourceManager.GetString("currentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to season.txt.
        /// </summary>
        internal static string currentSeason {
            get {
                return ResourceManager.GetString("currentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dt.
        /// </summary>
        internal static string dataPath {
            get {
                return ResourceManager.GetString("dataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msc.xml.
        /// </summary>
        internal static string eventMiscFile {
            get {
                return ResourceManager.GetString("eventMiscFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gbl.xml.
        /// </summary>
        internal static string globalSummaryFile {
            get {
                return ResourceManager.GetString("globalSummaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nmcfg.xml.
        /// </summary>
        internal static string normalisationConfiguration {
            get {
                return ResourceManager.GetString("normalisationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raw.txt.
        /// </summary>
        internal static string rawEventDataFile {
            get {
                return ResourceManager.GetString("rawEventDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rescfg.xml.
        /// </summary>
        internal static string resultsConfiguration {
            get {
                return ResourceManager.GetString("resultsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rt.txt.
        /// </summary>
        internal static string rootDataFile {
            get {
                return ResourceManager.GetString("rootDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srcfg.xml.
        /// </summary>
        internal static string seriesConfiguration {
            get {
                return ResourceManager.GetString("seriesConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        internal static string xmlExtension {
            get {
                return ResourceManager.GetString("xmlExtension", resourceCulture);
            }
        }
    }
}
