//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandicapModel.Admin.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResultsPaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultsPaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandicapModel.Admin.IO.ResultsPaths", typeof(ResultsPaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        internal static string csvExtension {
            get {
                return ResourceManager.GetString("csvExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap.
        /// </summary>
        internal static string handicapTable {
            get {
                return ResourceManager.GetString("handicapTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobTrophyPoints.
        /// </summary>
        internal static string mobTrophyPointsTable {
            get {
                return ResourceManager.GetString("mobTrophyPointsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobTrophyPointsCurrent.
        /// </summary>
        internal static string mobTrophyPointsTableCurrentEvent {
            get {
                return ResourceManager.GetString("mobTrophyPointsTableCurrentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string nextNewRunner {
            get {
                return ResourceManager.GetString("nextNewRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string pointsTable {
            get {
                return ResourceManager.GetString("pointsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string resultsTable {
            get {
                return ResourceManager.GetString("resultsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string separator {
            get {
                return ResourceManager.GetString("separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultsSummary.
        /// </summary>
        internal static string summaryTable {
            get {
                return ResourceManager.GetString("summaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamTrophyPoints.
        /// </summary>
        internal static string teamTrophyPointsTable {
            get {
                return ResourceManager.GetString("teamTrophyPointsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamTrophyPointsCurrent.
        /// </summary>
        internal static string teamTrophyPointsTableCurrentEvent {
            get {
                return ResourceManager.GetString("teamTrophyPointsTableCurrentEvent", resourceCulture);
            }
        }
    }
}
